name: PR Build with remaining tests

on:
  issue_comment:
    types:
      - created

jobs:
  build:
    if: github.event.issue.pull_request && github.event.comment.body == 'Build with remaining tests'
    permissions:
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: "refs/pull/${{ github.event.issue.number }}/head"
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up Gradle Build Action
        uses: gradle/gradle-build-action@v2
      - name: Build with PTS (remaining tests)
        run: ./gradlew build -Dpts.mode=REMAINING_TESTS
      - name: Update status check for Build with remaining tests
        if: always()
        run: |
          sha=$(git rev-parse HEAD)
          echo "Updating status for commit $sha"
          curl \
            --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/statuses/$sha \
            --header 'content-type: application/json' \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --data '{
              "state": "${{ job.status }}",
              "context": "Build With Remaining Tests", 
              "description": "Run PTS remaining tests before merge" 
              }'
